from typing import Union
from params_proto import Meta
from config.config import Cfg
import numpy as np
import math

def config_go1(Cnfg: Union[Cfg, Meta]):
    _ = Cnfg.init_state
    _.pos = [0.0, 0.0, 0.29]  # x,y,z [m]

    _ = Cnfg.asset
    if Cnfg.sim.use_gripper:
        _.urdf_path = 'asset/locoman/urdf/locoman.urdf'
        _.wbc_urdf_path = _.urdf_path
        _.dog_joint_idx = np.array([0, 1, 2, 6, 7, 8, 12, 13, 14, 15, 16, 17])
        _.manipulator_joint_idx = np.array([3, 4, 5, 9, 10, 11])
    else:
        _.urdf_path = 'asset/locoman/urdf/go1.urdf'
        _.wbc_urdf_path = _.urdf_path
        _.dog_joint_idx = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
        _.manipulator_joint_idx = np.array([])

    _.torso_names= ["base"]
    _.hip_names=["1_FR_hip", "2_FL_hip", "3_RR_hip", "4_RL_hip"]
    _.thigh_names=["1_FR_thigh", "2_FL_thigh", "3_RR_thigh", "4_RL_thigh"]
    _.calf_names=["1_FR_calf", "2_FL_calf", "3_RR_calf", "4_RL_calf"]
    _.foot_names=["1_FR_foot", "2_FL_foot", "3_RR_foot", "4_RL_foot"]
    _.eef_names=["1_FR_eef", "2_FL_eef"]

    _.hip_offsets = np.array([[0.1881, -0.04675, 0.], [0.1881, 0.04675, 0.], [-0.1881, -0.04675, 0.], [-0.1881, 0.04675, 0.]])
    _.l_hip = 0.08
    _.l_thi = 0.213
    _.l_cal = 0.213

    from robot.motors import MotorControlMode, MotorGroup, MotorModel  # import after using isaacgym
    _.motor_control_mode = MotorControlMode.HYBRID
    motor_control_mode = _.motor_control_mode
    kp = Cnfg.motor_control.real.kp if Cnfg.sim.use_real_robot else Cnfg.motor_control.sim.kp
    kd = Cnfg.motor_control.real.kd if Cnfg.sim.use_real_robot else Cnfg.motor_control.sim.kd
    kp_stance_loco = Cnfg.motor_control.real.kp_stance_loco if Cnfg.sim.use_real_robot else Cnfg.motor_control.sim.kp_stance_loco
    kd_stance_loco = Cnfg.motor_control.real.kd_stance_loco if Cnfg.sim.use_real_robot else Cnfg.motor_control.sim.kd_stance_loco
    kp_swing_loco = Cnfg.motor_control.real.kp_swing_loco if Cnfg.sim.use_real_robot else Cnfg.motor_control.sim.kp_swing_loco
    kd_swing_loco = Cnfg.motor_control.real.kd_swing_loco if Cnfg.sim.use_real_robot else Cnfg.motor_control.sim.kd_swing_loco
    kp_stance_mani = Cnfg.motor_control.real.kp_stance_mani if Cnfg.sim.use_real_robot else Cnfg.motor_control.sim.kp_stance_mani
    kd_stance_mani = Cnfg.motor_control.real.kd_stance_mani if Cnfg.sim.use_real_robot else Cnfg.motor_control.sim.kd_stance_mani
    kp_swing_mani = Cnfg.motor_control.real.kp_swing_mani if Cnfg.sim.use_real_robot else Cnfg.motor_control.sim.kp_swing_mani
    kd_swing_mani = Cnfg.motor_control.real.kd_swing_mani if Cnfg.sim.use_real_robot else Cnfg.motor_control.sim.kd_swing_mani
    Cnfg.motor_control.kp = kp
    Cnfg.motor_control.kd = kd
    Cnfg.motor_control.kp_stance_loco = kp_stance_loco
    Cnfg.motor_control.kd_stance_loco = kd_stance_loco
    Cnfg.motor_control.kp_swing_loco = kp_swing_loco
    Cnfg.motor_control.kd_swing_loco = kd_swing_loco
    Cnfg.motor_control.kp_stance_mani = kp_stance_mani
    Cnfg.motor_control.kd_stance_mani = kd_stance_mani
    Cnfg.motor_control.kp_swing_mani = kp_swing_mani
    Cnfg.motor_control.kd_swing_mani = kd_swing_mani
    motor_torque_delay_steps = 0

    init_joint_pos = [0.0, 0.9, -1.8, 0.0, 0.9, -1.8, 0.0, 0.9, -1.8, 0.0, 0.9, -1.8]
    # min_position = [-0.863, -0.686, -2.818, -0.863, -0.686, -2.818, -0.863, -0.686, -2.818, -0.863, -0.686, -2.818]
    # max_position = [0.863, 4.501, -0.888, 0.863, 4.501, -0.888, 0.863, 4.501, -0.888, 0.863, 4.501, -0.888]

    min_position = [-0.853, -0.676, -2.808, -0.853, -0.676, -2.808, -0.853, -0.676, -2.808, -0.853, -0.676, -2.808]
    max_position = [0.853, 4.491, -0.878, 0.853, 4.491, -0.878, 0.853, 4.491, -0.878, 0.853, 4.491, -0.878]

    min_velocity = [-30.1, -30.1, -20.06, -30.1, -30.1, -20.06, -30.1, -30.1, -20.06, -30.1, -30.1, -20.06]
    max_velocity = [30.1, 30.1, 20.06, 30.1, 30.1, 20.06, 30.1, 30.1, 20.06, 30.1, 30.1, 20.06]
    min_torque = [-23.7, -23.7, -35.55, -23.7, -23.7, -35.55, -23.7, -23.7, -35.55, -23.7, -23.7, -35.55]
    max_torque = [23.7, 23.7, 35.55, 23.7, 23.7, 35.55, 23.7, 23.7, 35.55, 23.7, 23.7, 35.55]
    
    Cnfg.init_joint_pos = init_joint_pos
    Cnfg.min_position = min_position
    Cnfg.max_position = max_position
    Cnfg.min_velocity = min_velocity
    Cnfg.max_velocity = max_velocity
    Cnfg.min_torque = min_torque
    Cnfg.max_torque = max_torque

    manipulator_init_joint_pose = Cfg.manipulator.reset_pos_sim
    manipulator_min_position = Cfg.manipulator.min_position
    manipulator_max_position = Cfg.manipulator.max_position
    manipulator_min_velocity = Cfg.manipulator.min_velocity
    manipulator_max_velocity = Cfg.manipulator.max_velocity
    manipulator_min_torque = Cfg.manipulator.min_torque
    manipulator_max_torque = Cfg.manipulator.max_torque

    if Cnfg.sim.use_gripper:
        _.motors = MotorGroup(device=Cnfg.sim.sim_device,
                        num_envs=Cnfg.sim.num_envs,
                        motors=(
                        MotorModel(
                            name="FR_hip_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[0],
                            min_position=min_position[0],
                            max_position=max_position[0],
                            min_velocity=min_velocity[0],
                            max_velocity=max_velocity[0],
                            min_torque=min_torque[0],
                            max_torque=max_torque[0],
                            kp=kp[0],
                            kd=kd[0],
                            kp_stance_loco=kp_stance_loco[0],
                            kd_stance_loco=kd_stance_loco[0],
                            kp_swing_loco=kp_swing_loco[0],
                            kd_swing_loco=kd_swing_loco[0],
                            kp_stance_mani=kp_stance_mani[0],
                            kd_stance_mani=kd_stance_mani[0],
                            kp_swing_mani=kp_swing_mani[0],
                            kd_swing_mani=kd_swing_mani[0],
                        ),
                        MotorModel(
                            name="FR_thigh_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[1],
                            min_position=min_position[1],
                            max_position=max_position[1],
                            min_velocity=min_velocity[1],
                            max_velocity=max_velocity[1],
                            min_torque=min_torque[1],
                            max_torque=max_torque[1],
                            kp=kp[1],
                            kd=kd[1],
                            kp_stance_loco=kp_stance_loco[1],
                            kd_stance_loco=kd_stance_loco[1],
                            kp_swing_loco=kp_swing_loco[1],
                            kd_swing_loco=kd_swing_loco[1],
                            kp_stance_mani=kp_stance_mani[1],
                            kd_stance_mani=kd_stance_mani[1],
                            kp_swing_mani=kp_swing_mani[1],
                            kd_swing_mani=kd_swing_mani[1],
                        ),
                        MotorModel(
                            name="FR_calf_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[2],
                            min_position=min_position[2],
                            max_position=max_position[2],
                            min_velocity=min_velocity[2],
                            max_velocity=max_velocity[2],
                            min_torque=min_torque[2],
                            max_torque=max_torque[2],
                            kp=kp[2],
                            kd=kd[2],
                            kp_stance_loco=kp_stance_loco[2],
                            kd_stance_loco=kd_stance_loco[2],
                            kp_swing_loco=kp_swing_loco[2],
                            kd_swing_loco=kd_swing_loco[2],
                            kp_stance_mani=kp_stance_mani[2],
                            kd_stance_mani=kd_stance_mani[2],
                            kp_swing_mani=kp_swing_mani[2],
                            kd_swing_mani=kd_swing_mani[2],
                        ),
                        MotorModel(
                            name="RM_joint_1",
                            motor_control_mode=motor_control_mode,
                            init_position=manipulator_init_joint_pose[0],
                            min_position=manipulator_min_position[0],
                            max_position=manipulator_max_position[0],
                            min_velocity=manipulator_min_velocity[0],
                            max_velocity=manipulator_max_velocity[0],
                            min_torque=manipulator_min_torque[0],
                            max_torque=manipulator_max_torque[0],
                            kp=kp[3],
                            kd=kd[3],
                            kp_stance_loco=kp_stance_loco[3],
                            kd_stance_loco=kd_stance_loco[3],
                            kp_swing_loco=kp_swing_loco[3],
                            kd_swing_loco=kd_swing_loco[3],
                            kp_stance_mani=kp_stance_mani[3],
                            kd_stance_mani=kd_stance_mani[3],
                            kp_swing_mani=kp_swing_mani[3],
                            kd_swing_mani=kd_swing_mani[3],
                        ),
                        MotorModel(
                            name="RM_joint_2",
                            motor_control_mode=motor_control_mode,
                            init_position=manipulator_init_joint_pose[1],
                            min_position=manipulator_min_position[1],
                            max_position=manipulator_max_position[1],
                            min_velocity=manipulator_min_velocity[1],
                            max_velocity=manipulator_max_velocity[1],
                            min_torque=manipulator_min_torque[1],
                            max_torque=manipulator_max_torque[1],
                            kp=kp[4],
                            kd=kd[4],
                            kp_stance_loco=kp_stance_loco[4],
                            kd_stance_loco=kd_stance_loco[4],
                            kp_swing_loco=kp_swing_loco[4],
                            kd_swing_loco=kd_swing_loco[4],
                            kp_stance_mani=kp_stance_mani[4],
                            kd_stance_mani=kd_stance_mani[4],
                            kp_swing_mani=kp_swing_mani[4],
                            kd_swing_mani=kd_swing_mani[4],
                        ),
                        MotorModel(
                            name="RM_joint_3",
                            motor_control_mode=motor_control_mode,
                            init_position=manipulator_init_joint_pose[2],
                            min_position=manipulator_min_position[2],
                            max_position=manipulator_max_position[2],
                            min_velocity=manipulator_min_velocity[2],
                            max_velocity=manipulator_max_velocity[2],
                            min_torque=manipulator_min_torque[2],
                            max_torque=manipulator_max_torque[2],
                            kp=kp[5],
                            kd=kd[5],
                            kp_stance_loco=kp_stance_loco[5],
                            kd_stance_loco=kd_stance_loco[5],
                            kp_swing_loco=kp_swing_loco[5],
                            kd_swing_loco=kd_swing_loco[5],
                            kp_stance_mani=kp_stance_mani[5],
                            kd_stance_mani=kd_stance_mani[5],
                            kp_swing_mani=kp_swing_mani[5],
                            kd_swing_mani=kd_swing_mani[5],
                        ),

                        MotorModel(
                            name="FL_hip_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[3],
                            min_position=min_position[3],
                            max_position=max_position[3],
                            min_velocity=min_velocity[3],
                            max_velocity=max_velocity[3],
                            min_torque=min_torque[3],
                            max_torque=max_torque[3],
                            kp=kp[0],
                            kd=kd[0],
                            kp_stance_loco=kp_stance_loco[0],
                            kd_stance_loco=kd_stance_loco[0],
                            kp_swing_loco=kp_swing_loco[0],
                            kd_swing_loco=kd_swing_loco[0],
                            kp_stance_mani=kp_stance_mani[0],
                            kd_stance_mani=kd_stance_mani[0],
                            kp_swing_mani=kp_swing_mani[0],
                            kd_swing_mani=kd_swing_mani[0],
                        ),
                        MotorModel(
                            name="FL_thigh_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[4],
                            min_position=min_position[4],
                            max_position=max_position[4],
                            min_velocity=min_velocity[4],
                            max_velocity=max_velocity[4],
                            min_torque=min_torque[4],
                            max_torque=max_torque[4],
                            kp=kp[1],
                            kd=kd[1],
                            kp_stance_loco=kp_stance_loco[1],
                            kd_stance_loco=kd_stance_loco[1],
                            kp_swing_loco=kp_swing_loco[1],
                            kd_swing_loco=kd_swing_loco[1],
                            kp_stance_mani=kp_stance_mani[1],
                            kd_stance_mani=kd_stance_mani[1],
                            kp_swing_mani=kp_swing_mani[1],
                            kd_swing_mani=kd_swing_mani[1],
                        ),
                        MotorModel(
                            name="FL_calf_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[5],
                            min_position=min_position[5],
                            max_position=max_position[5],
                            min_velocity=min_velocity[5],
                            max_velocity=max_velocity[5],
                            min_torque=min_torque[5],
                            max_torque=max_torque[5],
                            kp=kp[2],
                            kd=kd[2],
                            kp_stance_loco=kp_stance_loco[2],
                            kd_stance_loco=kd_stance_loco[2],
                            kp_swing_loco=kp_swing_loco[2],
                            kd_swing_loco=kd_swing_loco[2],
                            kp_stance_mani=kp_stance_mani[2],
                            kd_stance_mani=kd_stance_mani[2],
                            kp_swing_mani=kp_swing_mani[2],
                            kd_swing_mani=kd_swing_mani[2],
                        ),
                        MotorModel(
                            name="LM_joint_1",
                            motor_control_mode=motor_control_mode,
                            init_position=manipulator_init_joint_pose[4],
                            min_position=manipulator_min_position[4],
                            max_position=manipulator_max_position[4],
                            min_velocity=manipulator_min_velocity[4],
                            max_velocity=manipulator_max_velocity[4],
                            min_torque=manipulator_min_torque[4],
                            max_torque=manipulator_max_torque[4],
                            kp=kp[3],
                            kd=kd[3],
                            kp_stance_loco=kp_stance_loco[3],
                            kd_stance_loco=kd_stance_loco[3],
                            kp_swing_loco=kp_swing_loco[3],
                            kd_swing_loco=kd_swing_loco[3],
                            kp_stance_mani=kp_stance_mani[3],
                            kd_stance_mani=kd_stance_mani[3],
                            kp_swing_mani=kp_swing_mani[3],
                            kd_swing_mani=kd_swing_mani[3],
                        ),
                        MotorModel(
                            name="LM_joint_2",
                            motor_control_mode=motor_control_mode,
                            init_position=manipulator_init_joint_pose[5],
                            min_position=manipulator_min_position[5],
                            max_position=manipulator_max_position[5],
                            min_velocity=manipulator_min_velocity[5],
                            max_velocity=manipulator_max_velocity[5],
                            min_torque=manipulator_min_torque[5],
                            max_torque=manipulator_max_torque[5],
                            kp=kp[4],
                            kd=kd[4],
                            kp_stance_loco=kp_stance_loco[4],
                            kd_stance_loco=kd_stance_loco[4],
                            kp_swing_loco=kp_swing_loco[4],
                            kd_swing_loco=kd_swing_loco[4],
                            kp_stance_mani=kp_stance_mani[4],
                            kd_stance_mani=kd_stance_mani[4],
                            kp_swing_mani=kp_swing_mani[4],
                            kd_swing_mani=kd_swing_mani[4],
                        ),
                        MotorModel(
                            name="LM_joint_3",
                            motor_control_mode=motor_control_mode,
                            init_position=manipulator_init_joint_pose[6],
                            min_position=manipulator_min_position[6],
                            max_position=manipulator_max_position[6],
                            min_velocity=manipulator_min_velocity[6],
                            max_velocity=manipulator_max_velocity[6],
                            min_torque=manipulator_min_torque[6],
                            max_torque=manipulator_max_torque[6],
                            kp=kp[5],
                            kd=kd[5],
                            kp_stance_loco=kp_stance_loco[5],
                            kd_stance_loco=kd_stance_loco[5],
                            kp_swing_loco=kp_swing_loco[5],
                            kd_swing_loco=kd_swing_loco[5],
                            kp_stance_mani=kp_stance_mani[5],
                            kd_stance_mani=kd_stance_mani[5],
                            kp_swing_mani=kp_swing_mani[5],
                            kd_swing_mani=kd_swing_mani[5],
                        ),

                        MotorModel(
                            name="RR_hip_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[6],
                            min_position=min_position[6],
                            max_position=max_position[6],
                            min_velocity=min_velocity[6],
                            max_velocity=max_velocity[6],
                            min_torque=min_torque[6],
                            max_torque=max_torque[6],
                            kp=kp[0],
                            kd=kd[0],
                            kp_stance_loco=kp_stance_loco[0],
                            kd_stance_loco=kd_stance_loco[0],
                            kp_swing_loco=kp_swing_loco[0],
                            kd_swing_loco=kd_swing_loco[0],
                            kp_stance_mani=kp_stance_mani[0],
                            kd_stance_mani=kd_stance_mani[0],
                            kp_swing_mani=kp_swing_mani[0],
                            kd_swing_mani=kd_swing_mani[0],
                        ),
                        MotorModel(
                            name="RR_thigh_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[7],
                            min_position=min_position[7],
                            max_position=max_position[7],
                            min_velocity=min_velocity[7],
                            max_velocity=max_velocity[7],
                            min_torque=min_torque[7],
                            max_torque=max_torque[7],
                            kp=kp[1],
                            kd=kd[1],
                            kp_stance_loco=kp_stance_loco[1],
                            kd_stance_loco=kd_stance_loco[1],
                            kp_swing_loco=kp_swing_loco[1],
                            kd_swing_loco=kd_swing_loco[1],
                            kp_stance_mani=kp_stance_mani[1],
                            kd_stance_mani=kd_stance_mani[1],
                            kp_swing_mani=kp_swing_mani[1],
                            kd_swing_mani=kd_swing_mani[1],
                        ),
                        MotorModel(
                            name="RR_calf_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[8],
                            min_position=min_position[8],
                            max_position=max_position[8],
                            min_velocity=min_velocity[8],
                            max_velocity=max_velocity[8],
                            min_torque=min_torque[8],
                            max_torque=max_torque[8],
                            kp=kp[2],
                            kd=kd[2],
                            kp_stance_loco=kp_stance_loco[2],
                            kd_stance_loco=kd_stance_loco[2],
                            kp_swing_loco=kp_swing_loco[2],
                            kd_swing_loco=kd_swing_loco[2],
                            kp_stance_mani=kp_stance_mani[2],
                            kd_stance_mani=kd_stance_mani[2],
                            kp_swing_mani=kp_swing_mani[2],
                            kd_swing_mani=kd_swing_mani[2],
                        ),
                        MotorModel(
                            name="RL_hip_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[9],
                            min_position=min_position[9],
                            max_position=max_position[9],
                            min_velocity=min_velocity[9],
                            max_velocity=max_velocity[9],
                            min_torque=min_torque[9],
                            max_torque=max_torque[9],
                            kp=kp[0],
                            kd=kd[0],
                            kp_stance_loco=kp_stance_loco[0],
                            kd_stance_loco=kd_stance_loco[0],
                            kp_swing_loco=kp_swing_loco[0],
                            kd_swing_loco=kd_swing_loco[0],
                            kp_stance_mani=kp_stance_mani[0],
                            kd_stance_mani=kd_stance_mani[0],
                            kp_swing_mani=kp_swing_mani[0],
                            kd_swing_mani=kd_swing_mani[0],
                        ),
                        MotorModel(
                            name="RL_thigh_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[10],
                            min_position=min_position[10],
                            max_position=max_position[10],
                            min_velocity=min_velocity[10],
                            max_velocity=max_velocity[10],
                            min_torque=min_torque[10],
                            max_torque=max_torque[10],
                            kp=kp[1],
                            kd=kd[1],
                            kp_stance_loco=kp_stance_loco[1],
                            kd_stance_loco=kd_stance_loco[1],
                            kp_swing_loco=kp_swing_loco[1],
                            kd_swing_loco=kd_swing_loco[1],
                            kp_stance_mani=kp_stance_mani[1],
                            kd_stance_mani=kd_stance_mani[1],
                            kp_swing_mani=kp_swing_mani[1],
                            kd_swing_mani=kd_swing_mani[1],
                        ),
                        MotorModel(
                            name="RL_calf_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[11],
                            min_position=min_position[11],
                            max_position=max_position[11],
                            min_velocity=min_velocity[11],
                            max_velocity=max_velocity[11],
                            min_torque=min_torque[11],
                            max_torque=max_torque[11],
                            kp=kp[2],
                            kd=kd[2],
                            kp_stance_loco=kp_stance_loco[2],
                            kd_stance_loco=kd_stance_loco[2],
                            kp_swing_loco=kp_swing_loco[2],
                            kd_swing_loco=kd_swing_loco[2],
                            kp_stance_mani=kp_stance_mani[2],
                            kd_stance_mani=kd_stance_mani[2],
                            kp_swing_mani=kp_swing_mani[2],
                            kd_swing_mani=kd_swing_mani[2],
                        ), ), torque_delay_steps=motor_torque_delay_steps)
    else:
        _.motors = MotorGroup(device=Cnfg.sim.sim_device,
                        num_envs=Cnfg.sim.num_envs,
                        motors=(
                        MotorModel(
                            name="FR_hip_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[0],
                            min_position=min_position[0],
                            max_position=max_position[0],
                            min_velocity=min_velocity[0],
                            max_velocity=max_velocity[0],
                            min_torque=min_torque[0],
                            max_torque=max_torque[0],
                            kp=kp[0],
                            kd=kd[0],
                            kp_stance_loco=kp_stance_loco[0],
                            kd_stance_loco=kd_stance_loco[0],
                            kp_swing_loco=kp_swing_loco[0],
                            kd_swing_loco=kd_swing_loco[0],
                            kp_stance_mani=kp_stance_mani[0],
                            kd_stance_mani=kd_stance_mani[0],
                            kp_swing_mani=kp_swing_mani[0],
                            kd_swing_mani=kd_swing_mani[0],
                        ),
                        MotorModel(
                            name="FR_thigh_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[1],
                            min_position=min_position[1],
                            max_position=max_position[1],
                            min_velocity=min_velocity[1],
                            max_velocity=max_velocity[1],
                            min_torque=min_torque[1],
                            max_torque=max_torque[1],
                            kp=kp[1],
                            kd=kd[1],
                            kp_stance_loco=kp_stance_loco[1],
                            kd_stance_loco=kd_stance_loco[1],
                            kp_swing_loco=kp_swing_loco[1],
                            kd_swing_loco=kd_swing_loco[1],
                            kp_stance_mani=kp_stance_mani[1],
                            kd_stance_mani=kd_stance_mani[1],
                            kp_swing_mani=kp_swing_mani[1],
                            kd_swing_mani=kd_swing_mani[1],
                        ),
                        MotorModel(
                            name="FR_calf_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[2],
                            min_position=min_position[2],
                            max_position=max_position[2],
                            min_velocity=min_velocity[2],
                            max_velocity=max_velocity[2],
                            min_torque=min_torque[2],
                            max_torque=max_torque[2],
                            kp=kp[2],
                            kd=kd[2],
                            kp_stance_loco=kp_stance_loco[2],
                            kd_stance_loco=kd_stance_loco[2],
                            kp_swing_loco=kp_swing_loco[2],
                            kd_swing_loco=kd_swing_loco[2],
                            kp_stance_mani=kp_stance_mani[2],
                            kd_stance_mani=kd_stance_mani[2],
                            kp_swing_mani=kp_swing_mani[2],
                            kd_swing_mani=kd_swing_mani[2],
                        ),
                        MotorModel(
                            name="FL_hip_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[3],
                            min_position=min_position[3],
                            max_position=max_position[3],
                            min_velocity=min_velocity[3],
                            max_velocity=max_velocity[3],
                            min_torque=min_torque[3],
                            max_torque=max_torque[3],
                            kp=kp[0],
                            kd=kd[0],
                            kp_stance_loco=kp_stance_loco[0],
                            kd_stance_loco=kd_stance_loco[0],
                            kp_swing_loco=kp_swing_loco[0],
                            kd_swing_loco=kd_swing_loco[0],
                            kp_stance_mani=kp_stance_mani[0],
                            kd_stance_mani=kd_stance_mani[0],
                            kp_swing_mani=kp_swing_mani[0],
                            kd_swing_mani=kd_swing_mani[0],
                        ),
                        MotorModel(
                            name="FL_thigh_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[4],
                            min_position=min_position[4],
                            max_position=max_position[4],
                            min_velocity=min_velocity[4],
                            max_velocity=max_velocity[4],
                            min_torque=min_torque[4],
                            max_torque=max_torque[4],
                            kp=kp[1],
                            kd=kd[1],
                            kp_stance_loco=kp_stance_loco[1],
                            kd_stance_loco=kd_stance_loco[1],
                            kp_swing_loco=kp_swing_loco[1],
                            kd_swing_loco=kd_swing_loco[1],
                            kp_stance_mani=kp_stance_mani[1],
                            kd_stance_mani=kd_stance_mani[1],
                            kp_swing_mani=kp_swing_mani[1],
                            kd_swing_mani=kd_swing_mani[1],
                        ),
                        MotorModel(
                            name="FL_calf_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[5],
                            min_position=min_position[5],
                            max_position=max_position[5],
                            min_velocity=min_velocity[5],
                            max_velocity=max_velocity[5],
                            min_torque=min_torque[5],
                            max_torque=max_torque[5],
                            kp=kp[2],
                            kd=kd[2],
                            kp_stance_loco=kp_stance_loco[2],
                            kd_stance_loco=kd_stance_loco[2],
                            kp_swing_loco=kp_swing_loco[2],
                            kd_swing_loco=kd_swing_loco[2],
                            kp_stance_mani=kp_stance_mani[2],
                            kd_stance_mani=kd_stance_mani[2],
                            kp_swing_mani=kp_swing_mani[2],
                            kd_swing_mani=kd_swing_mani[2],
                        ),
                        MotorModel(
                            name="RR_hip_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[6],
                            min_position=min_position[6],
                            max_position=max_position[6],
                            min_velocity=min_velocity[6],
                            max_velocity=max_velocity[6],
                            min_torque=min_torque[6],
                            max_torque=max_torque[6],
                            kp=kp[0],
                            kd=kd[0],
                            kp_stance_loco=kp_stance_loco[0],
                            kd_stance_loco=kd_stance_loco[0],
                            kp_swing_loco=kp_swing_loco[0],
                            kd_swing_loco=kd_swing_loco[0],
                            kp_stance_mani=kp_stance_mani[0],
                            kd_stance_mani=kd_stance_mani[0],
                            kp_swing_mani=kp_swing_mani[0],
                            kd_swing_mani=kd_swing_mani[0],
                        ),
                        MotorModel(
                            name="RR_thigh_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[7],
                            min_position=min_position[7],
                            max_position=max_position[7],
                            min_velocity=min_velocity[7],
                            max_velocity=max_velocity[7],
                            min_torque=min_torque[7],
                            max_torque=max_torque[7],
                            kp=kp[1],
                            kd=kd[1],
                            kp_stance_loco=kp_stance_loco[1],
                            kd_stance_loco=kd_stance_loco[1],
                            kp_swing_loco=kp_swing_loco[1],
                            kd_swing_loco=kd_swing_loco[1],
                            kp_stance_mani=kp_stance_mani[1],
                            kd_stance_mani=kd_stance_mani[1],
                            kp_swing_mani=kp_swing_mani[1],
                            kd_swing_mani=kd_swing_mani[1],
                        ),
                        MotorModel(
                            name="RR_calf_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[8],
                            min_position=min_position[8],
                            max_position=max_position[8],
                            min_velocity=min_velocity[8],
                            max_velocity=max_velocity[8],
                            min_torque=min_torque[8],
                            max_torque=max_torque[8],
                            kp=kp[2],
                            kd=kd[2],
                            kp_stance_loco=kp_stance_loco[2],
                            kd_stance_loco=kd_stance_loco[2],
                            kp_swing_loco=kp_swing_loco[2],
                            kd_swing_loco=kd_swing_loco[2],
                            kp_stance_mani=kp_stance_mani[2],
                            kd_stance_mani=kd_stance_mani[2],
                            kp_swing_mani=kp_swing_mani[2],
                            kd_swing_mani=kd_swing_mani[2],
                        ),
                        MotorModel(
                            name="RL_hip_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[9],
                            min_position=min_position[9],
                            max_position=max_position[9],
                            min_velocity=min_velocity[9],
                            max_velocity=max_velocity[9],
                            min_torque=min_torque[9],
                            max_torque=max_torque[9],
                            kp=kp[0],
                            kd=kd[0],
                            kp_stance_loco=kp_stance_loco[0],
                            kd_stance_loco=kd_stance_loco[0],
                            kp_swing_loco=kp_swing_loco[0],
                            kd_swing_loco=kd_swing_loco[0],
                            kp_stance_mani=kp_stance_mani[0],
                            kd_stance_mani=kd_stance_mani[0],
                            kp_swing_mani=kp_swing_mani[0],
                            kd_swing_mani=kd_swing_mani[0],
                        ),
                        MotorModel(
                            name="RL_thigh_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[10],
                            min_position=min_position[10],
                            max_position=max_position[10],
                            min_velocity=min_velocity[10],
                            max_velocity=max_velocity[10],
                            min_torque=min_torque[10],
                            max_torque=max_torque[10],
                            kp=kp[1],
                            kd=kd[1],
                            kp_stance_loco=kp_stance_loco[1],
                            kd_stance_loco=kd_stance_loco[1],
                            kp_swing_loco=kp_swing_loco[1],
                            kd_swing_loco=kd_swing_loco[1],
                            kp_stance_mani=kp_stance_mani[1],
                            kd_stance_mani=kd_stance_mani[1],
                            kp_swing_mani=kp_swing_mani[1],
                            kd_swing_mani=kd_swing_mani[1],
                        ),
                        MotorModel(
                            name="RL_calf_joint",
                            motor_control_mode=motor_control_mode,
                            init_position=init_joint_pos[11],
                            min_position=min_position[11],
                            max_position=max_position[11],
                            min_velocity=min_velocity[11],
                            max_velocity=max_velocity[11],
                            min_torque=min_torque[11],
                            max_torque=max_torque[11],
                            kp=kp[2],
                            kd=kd[2],
                            kp_stance_loco=kp_stance_loco[2],
                            kd_stance_loco=kd_stance_loco[2],
                            kp_swing_loco=kp_swing_loco[2],
                            kd_swing_loco=kd_swing_loco[2],
                            kp_stance_mani=kp_stance_mani[2],
                            kd_stance_mani=kd_stance_mani[2],
                            kp_swing_mani=kp_swing_mani[2],
                            kd_swing_mani=kd_swing_mani[2],
                        ), ), torque_delay_steps=motor_torque_delay_steps)


